### ISSUE TITLE
Switch to local contenta, error in console.

### ISSUE THREAD

**Issue by rick02840** [contentacms/contenta_angular#93]
I altered endpoints to use my local install of contenta in these files:
```
ngsw-manifest.json
src/environments/environment.prod.js
src/environments/environment.js
```
I see json data fine at https://contenta:8890/api/recipes
But see error below in console for http://localhost:4200/recipes     ...no content is loaded.
Thanks,
Rick

```
Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
recipes:1 XMLHttpRequest cannot load https://contenta:8890/api/recipes?page%5Blimit%5D=6&include=image%2Ccategory%2Ctags%2Cimage.field_image%2Cimage.imageFile. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 405.
```

**Comment by joaogarin** [comment]
It seems as as you are running against localhost but the contenta local installation has no CORS setup for this URL.

Maybe you can ask in the contenta chat or in https://github.com/contentacms/contenta_jsonapi

The issue where this was discussed was in https://github.com/contentacms/contenta_jsonapi/issues/43 and I think that it should be allowing by default for every localhost port, so don't know why you are still running into this error.

**Comment by joaogarin** [comment]
You should be able to see your CORS settings in your services.yml file in the "cors.config" setting

**Comment by rick02840** [comment]
Thank you, it's working now. 
I changed these:
```
enabled:false > enabled_true
allowedHeaders: []  > allowedHeaders: ['*']
allowedMethods: []  > allowedMethods: ['*']
```
in web/sites/default/services.yml
...and cleared cache.
```
 cors.config:
    enabled: true
    # Specify allowed headers, like 'x-allowed-header'.
    allowedHeaders: ['*']
    # Specify allowed request methods, specify ['*'] to allow all possible ones.
    allowedMethods: ['*']
    # Configure requests allowed from specific origins.
    allowedOrigins: ['*']
    # Sets the Access-Control-Expose-Headers header.
    exposedHeaders: false
    # Sets the Access-Control-Max-Age header.
    maxAge: false
    # Sets the Access-Control-Allow-Credentials header.
    supportsCredentials: false
```
